version = 3

[noTickViewDistance]
	maxConcurrentChunkLoads = 2

[ioSystem]
	gcFreeChunkSerializer = false

[clientSideConfig]

	[clientSideConfig.modifyMaxVDConfig]
		enabled = false
		enableExtRenderDistanceProtocol = false
